version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"  # Проброс порту для доступу ззовні
    volumes:
      - .:/app  # Монтую поточну директорію на контейнер
    environment:
      FLASK_ENV: development  # Вказуємо Flask працювати в режимі розробки
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-files.rule=Host(`lili.borukh.net`)"
    restart: always  # Автоматичний перезапуск, якщо контейнер зупиняється

